### ISSUE TITLE
Widget only displays battery prefix

### ISSUE THREAD

**Issue by ghost** [coldfix/awesome.battery-widget#17]
Title is self explainatory. Widget always displays battery_prefix regardless of whether the ac cord is plugged in or not.

    > awesome --version
    awesome v4.2-289-g98e59225 (Human after all)
     • Compiled against Lua 5.3.4 (running with Lua 5.3)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.6
     • LGI version: 0.9.2

    > lua -v
    Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio

Nice work btw. Keep it up.

**Comment by coldfix** [comment]
Hi,

I assume you mean the widget displays either of the strings `"AC: "` or `"Bat: "`, correctly depending on whether cord is plugged in, but missing the percentage? (sorry it wasn't 100% clear to me)

Can you show the output of `ls -la /sys/class/power_supply` and the code that instanciates your battery widget in the `awesome/rc.lua`?

Best, Thomas

**Comment by coldfix** [comment]
Oh, I think I misread. You mean that it always shows `"Bat: "` including the percentage, right?

In this case, can you check whether the `/sys/class/power_supply/BAT0/AC/` folder exists (probably a symlink).

If so, what does `cat /sys/class/power_supply/BAT0/AC/online` show?
If not, what does  `cat /sys/class/power_supply/AC/online` show?

**Comment by ghost** [comment]
Sorry for late reply, been travelling and away from my laptop. Will provide you with the info soon.

**Comment by ghost** [comment]
Hi,

No the AC directory doesn't exist anywhere, but there's a directory named ACAD along with the BAT directory, and it contains a file named `online` which contains 1 if the power cable is plugged in. Changing 'AC/online'  to 'ACAD/online'  fixes the problem for me, but might break it for someone else.

**Comment by coldfix** [comment]
Great. I added the fallback to ACAD. (Unfortunately, I don't know enough about this topic to be sure if there are any other possibilities). Thanks a lot for reporting!
