### ISSUE TITLE
Widget Fails on Battery Power (Pinebook Pro)

### ISSUE THREAD

**Issue by ZachIndigo** [coldfix/awesome.battery-widget#30]
I am using a Pinebook Pro, which has a different battery device name than normal (/sys/class/power_supply/cw2015-battery/ instead of /sys/class/power_supply/BATx), which I adjusted for in my Awesome config. When running on AC power, the widget works perfectly. However, when just using the battery, the widget crashes with .config/awesome/battery-widget/init.lua:240: attempt to perform arithmetic on a nil value (field 'charge').

The relevant section of my config is

`local battery_widget = require("battery-widget")
local BAT0 = battery_widget { adapter = "cw2015-battery", ac = "dc-charger", timeout = 10, listen = true }

...

s.mywibox:setup {
...
( -- Right widgets
BAT0,
...`

**Comment by ZachIndigo** [comment]
I was able to fix this by wrapping the `ctx.time_left = ctx.charge / ctx.rate` in an if statement (specifically `if not ctx.charge == nil then ... end`

**Comment by coldfix** [comment]
Hi,

out of curiosity, can you check the output of

```
cat /sys/class/power_supply/cw2015-battery/energy_now
```

each on AC and on battery power.

(or `.../charge_now` if `energy_now` doesn't exist)
