### ISSUE TITLE
Font to small.

### ISSUE THREAD

**Issue by AnantGupta384** [coldfix/awesome.battery-widget#31]
Using this widget in my wibar, I am not sure why, but the font of the widget is very small. I guess it is not respecting my bar config font & size. Here is my bar 
![image](https://user-images.githubusercontent.com/71361442/129436101-07f3f332-ac2e-4955-a97c-b3a22d32aea0.png)
Some stuff which might help
``` lua
-- Battery
local battery_widget = require("battery-widget")
local BAT0 = battery_widget { adapter = "BAT0", ac = "AC" }

battery_widget {
    ac = "AC",
    adapter = "BAT0",
    ac_prefix = "AC: ",
    battery_prefix = "Bat: ",
    percent_colors = {
        { 25, "red"   },
        { 50, "orange"},
        {999, "green" },
    },
    listen = true,
    timeout = 10,
    widget_text = "${AC_BAT}${color_on}${percent}%${color_off}",
    widget_text = '<span font="Roboto Mono 10">${AC_BAT}</span>${color_on}${percent}%${color_off}',
    tooltip_text = "Battery ${state}${time_est}\nCapacity: ${capacity_percent}%",
    alert_threshold = 5,
    alert_timeout = 0,
    alert_title = "Low battery !",
    alert_text = "${AC_BAT}${time_est}"
}
```
``` lua
    -- Add widgets to the wibox
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            s.mytaglist,
            s.mypromptbox,
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            BAT0,
            mytextclock,
        },
    }
end)
-- }}}
```

Thanks in advance :)

**Comment by coldfix** [comment]
Hi,

did you try passing the font in the `widget_font` argument instead of manually creating a span in `widget_text`?

**Comment by coldfix** [comment]
By the way, your setup code looks weird:

it first creates a battery widget instance with very few parameters and stores it in the `BAT0` variable, then after, creates another instance with many parameters (even passing the `widget_text` argument twice), but doesn't store it in any variable, and later goes on to use just the object that was created with few parameters.
