### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by itzjustalan** [coldfix/awesome.battery-widget#32]
![photo6239945620156691145](https://user-images.githubusercontent.com/62483921/197225876-1ade384f-fbe2-431f-9227-e71cfd4825bb.jpg)

I cloned the repo into ./widgets/ and I imorted it using ```local battery_widget = pcall(require, "widgets.battery-widget")``` but as soon as I reload the wm I get this error and the the wm fall back to the default config

**Comment by coldfix** [comment]
What is your code related to usage of the widget?

**Comment by itzjustalan** [comment]
```
local _, battery_widget = pcall(require, "widgets.battery-widget")

...
	-- Add widgets to the wibox
	s.mywibox:setup({
		layout = wibox.layout.align.horizontal,
		{ -- Left widgets
			layout = wibox.layout.fixed.horizontal,
			mylauncher,
			s.mytaglist,
			s.mypromptbox,
		},
		s.mytasklist, -- Middle widget
		{ -- Right widgets
			layout = wibox.layout.fixed.horizontal,
			mykeyboardlayout,
      battery_widget,
			mytextclock,
      wibox.widget.systray(),
			s.mylayoutbox,
		},
	})

```

**Comment by coldfix** [comment]
you'll need to pass it as `battery_widget {}` to `mywibox:setup`, i.e. invoke the constructor function returned by the module, c.f. README.

**Comment by itzjustalan** [comment]
Thank you that worked!
