### ISSUE TITLE
Unicode character support assistance

### ISSUE THREAD

**Issue by ThomasDelSantoONeill** [coldfix/awesome.battery-widget#33]
Hi, I am new to arch and I was wondering if there are any dependencies or unicode character support packages that work well with the widget. When I change the prefix "Bat:" to "U+1F50B" to display a battery icon, the widget renders "U+1F50B" instead of the icon. Any suggestion would be very much appreciated.

**Comment by coldfix** [comment]
The easiest method would be to just write out the unicode character into the string as is, i.e. something like this:

```
local my_battery_widget = require('deficient.battery-widget') {
    battery_prefix = '🔋',
}
```

In any case, the font you're using will need to have support for the corresponding symbols.

**Comment by coldfix** [comment]
(alternatively, if you don't want unicode symbols in your code, write it as an escape sequence `battery_prefix = '\u{1F50B}'`, I also had to look it up how it looks in lua)

**Comment by ThomasDelSantoONeill** [comment]
Thank you ever so much for the quick reply coldfix. The problem is that \u{1F50B} renders a strange symbol rather than the battery icon. My problem has to do more with unicod character in archlinux but I am unaware on how to install/enable unicode character support. Any ideas?

**Comment by ThomasDelSantoONeill** [comment]
I fix the issue by installing the noto-fonts-emoji package from https://wiki.archlinux.org/title/Fonts#Non-latin_scripts. The issue was than I had no support for rendering unicode characters. Thank you for your availability and widget :)
