### ISSUE TITLE
How to add this to the wibar?

### ISSUE THREAD

**Issue by wucke13** [coldfix/awesome.battery-widget#9]
Using `right_layout:add(battery.widget)` throws an error cause there is no object `right_layout`. How may I add it to the wibar, after initial setup?

**Comment by coldfix** [comment]
depends how your `rc.lua` looks like. The current default contains a section which looks like:

```
    awful.titlebar(c) : setup {
        { -- Left
            ...
        },
        { -- Middle
            ...
        },
        { -- Right
            ...
        },
        layout = wibox.layout.align.horizontal
}
```

you can insert `battery.widget` there as you like it.

The usage example from the README is from a time where the default looked different, I believe.

**Comment by coldfix** [comment]
Oh, forget what I said! This is for the client titlebars, not the wibox. 

Instead, look for:

```lua
s.mywibox:setup {

        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            ...
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            ...
        },
}
```

**Comment by wucke13** [comment]
I know that I can add it this way, however I would like to add it after the initial run of `s.mywibox:setup`. Is that still possible? The reason is that I use the same rc.lua for both desktop and laptop. I wrote a little lua snippet which finds out on which device I am, now I would like to add it to the wibox.

**Comment by coldfix** [comment]
Oh. Well, you can restructure your init code like this:

```
  local right_layout = {
      ...
  }
  if laptop then table.insert(right_layout, battery.widget) end
  s.mywibox:setup {
      layout = wibox.layout.align.horizontal,
      left_layout,
      nil,
      right_layout,
  }
```

Or just look into the awesome [documentation](https://awesomewm.org/doc/api/classes/awful.wibar.html).
